/* Configuration for ada_blink_demo generated by Alire */
#ifndef ADA_BLINK_DEMO_CONFIG_H
#define ADA_BLINK_DEMO_CONFIG_H

#define CRATE_VERSION "0.1.0-dev"
#define CRATE_NAME "ada_blink_demo"

#define ALIRE_HOST_OS "linux"

#define ALIRE_HOST_ARCH "aarch64"

#define ALIRE_HOST_DISTRO "debian"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  3

#endif
